version: "3.7"

services:
  scraper:
    container_name: scraper
    image: lindenhoney/linden-honey-scraper:latest
    build: .
    ports:
      - 80:8080
    networks:
      - internal

networks:
  internal:
    driver: bridge
